/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author novad
 */

public class FormularioVehiculo extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form insertarTrabajador
     */
    private boolean confirmarInsertar;
    public FormularioVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        confirmarInsertar=false;
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfMotor = new javax.swing.JTextField();
        jtfConsumo = new javax.swing.JTextField();
        jlBastidor = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jlPotencia = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlTiempoDedicado = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jtfTiempoDedicado = new javax.swing.JTextField();
        jlMotor = new javax.swing.JLabel();
        jlDniTrabajadorAsignado = new javax.swing.JLabel();
        jlFormularioVehiculo = new javax.swing.JLabel();
        jtfDniTrabajadorAsignado = new javax.swing.JTextField();
        jtfBastidor = new javax.swing.JTextField();
        jtfMatricula = new javax.swing.JTextField();
        jlConsumo = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jlFechaEntrada = new javax.swing.JLabel();
        jtfModelo = new javax.swing.JTextField();
        jtfPotencia = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jtfAceite = new javax.swing.JTextField();
        jlAceite = new javax.swing.JLabel();
        jtfCarburante = new javax.swing.JTextField();
        jlCarburante = new javax.swing.JLabel();
        jsFechaEntrada = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtfMotor.setEditable(false);

        jtfConsumo.setEditable(false);

        jlBastidor.setForeground(new java.awt.Color(0, 102, 204));
        jlBastidor.setText("Bastidor");

        jlMatricula.setForeground(new java.awt.Color(0, 102, 204));
        jlMatricula.setText("Matrícula");

        jlPotencia.setForeground(new java.awt.Color(0, 102, 204));
        jlPotencia.setText("Potencia");

        jlMarca.setForeground(new java.awt.Color(0, 102, 204));
        jlMarca.setText("Marca");

        jlTiempoDedicado.setForeground(new java.awt.Color(0, 102, 204));
        jlTiempoDedicado.setText("Tiempo dedicado");

        jlModelo.setForeground(new java.awt.Color(0, 102, 204));
        jlModelo.setText("Modelo");

        jtfTiempoDedicado.setEditable(false);

        jlMotor.setForeground(new java.awt.Color(0, 102, 204));
        jlMotor.setText("Motor");

        jlDniTrabajadorAsignado.setForeground(new java.awt.Color(0, 102, 204));
        jlDniTrabajadorAsignado.setText("DNI del trabajador asignado");

        jlFormularioVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlFormularioVehiculo.setForeground(new java.awt.Color(0, 102, 204));
        jlFormularioVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFormularioVehiculo.setText("Insertar Vehículo");

        jtfDniTrabajadorAsignado.setEditable(false);

        jtfBastidor.setEditable(false);

        jtfMatricula.setEditable(false);

        jlConsumo.setForeground(new java.awt.Color(0, 102, 204));
        jlConsumo.setText("Consumo");

        jtfMarca.setEditable(false);

        jlFechaEntrada.setForeground(new java.awt.Color(0, 102, 204));
        jlFechaEntrada.setText("Fecha de entrada");

        jtfModelo.setEditable(false);

        jtfPotencia.setEditable(false);

        jbCancelar.setText("Cancelar");

        jbAceptar.setText("Aceptar");

        jtfAceite.setEditable(false);

        jlAceite.setForeground(new java.awt.Color(0, 102, 204));
        jlAceite.setText("Aceite");

        jtfCarburante.setEditable(false);

        jlCarburante.setForeground(new java.awt.Color(0, 102, 204));
        jlCarburante.setText("Carburante");

        jsFechaEntrada.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlFormularioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlConsumo)
                            .addComponent(jtfConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBastidor)
                            .addComponent(jtfBastidor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMotor)
                            .addComponent(jtfMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMarca)
                            .addComponent(jlCarburante)
                            .addComponent(jtfCarburante, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPotencia)
                            .addComponent(jlMatricula)
                            .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlModelo)
                            .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAceite)
                            .addComponent(jtfAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFechaEntrada)
                                    .addComponent(jsFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTiempoDedicado)
                                    .addComponent(jtfTiempoDedicado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDniTrabajadorAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlDniTrabajadorAsignado))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlFormularioVehiculo)
                        .addGap(41, 41, 41)
                        .addComponent(jlMatricula)
                        .addGap(12, 12, 12)
                        .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlPotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAceite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAceite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jlBastidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBastidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlMotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCarburante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCarburante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlConsumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlFechaEntrada)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jlTiempoDedicado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTiempoDedicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addComponent(jlDniTrabajadorAsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDniTrabajadorAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioVehiculo dialog = new FormularioVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==jbAceptar)
        {
            confirmarInsertar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarInsertar=false;
            this.dispose();
        }
        
    }
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarInsertar;
    }
    //Para utilizar el formulario con la función modificar y colocarle los datos que ya existen.
    public void setTextoTitulo(String texto){
        jlFormularioVehiculo.setText(texto);
    }
    public void setTextoBastidor(String texto){
        jtfBastidor.setText(texto);
    }
    public void setTextoMatricula(String texto){
        jtfMatricula.setText(texto);
    }
    public void setTextoMarca(String texto){
        jtfMarca.setText(texto);
    }
    public void setTextoModelo(String texto){
        jtfModelo.setText(texto);
    }
    public void setTextoMotor(String texto){
        jtfMotor.setText(texto);
    }
    public void setTextoPotencia(String texto){
        jtfPotencia.setText(texto);
    }
    public void setTextoCarburante(String texto){
        jtfCarburante.setText(texto);
    }
    public void setTextoAceite(String texto){
        jtfAceite.setText(texto);
    }
    public void setTextoConsumo(String texto){
        jtfConsumo.setText(texto);
    }
    public void setTextoFechaEntrada(Date texto){
        jsFechaEntrada.setValue(texto);
    }
    public void setTextoTiempoDedicado(String texto){
        jtfTiempoDedicado.setText(texto);
    }
    public void setTextoDniTrabajadorAsignado(String texto){
        jtfDniTrabajadorAsignado.setText(texto);
    }
    
    //Funciones para extraer los datos del formulario.
     public String getBastidor() {
        return jtfBastidor.getText();
    }
     public String getMatricula() {
        return jtfMatricula.getText();
    }
    public String getMarca() {
        return jtfMarca.getText();
    }

    public String getModelo() {
        return jtfModelo.getText();
    }
    public String getMotor() {
        return jtfMotor.getText();
    }
    public String getPotencia() {
        return jtfPotencia.getText();
    }
    public String getCarburante() {
        return jtfCarburante.getText();
    }
    public String getAceite() {
        return jtfAceite.getText();
    }
    public String getConsumo() {
        return jtfConsumo.getText();
    }
    public Date getFechaEntrada() {
        return (Date) jsFechaEntrada.getValue();
    }
    public String getTiempoDedicado() {
        return jtfTiempoDedicado.getText();
    }
    public String getDniTrabajadorAsignado() {
        return jtfDniTrabajadorAsignado.getText();
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlAceite;
    private javax.swing.JLabel jlBastidor;
    private javax.swing.JLabel jlCarburante;
    private javax.swing.JLabel jlConsumo;
    private javax.swing.JLabel jlDniTrabajadorAsignado;
    private javax.swing.JLabel jlFechaEntrada;
    private javax.swing.JLabel jlFormularioVehiculo;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlMotor;
    private javax.swing.JLabel jlPotencia;
    private javax.swing.JLabel jlTiempoDedicado;
    private javax.swing.JSpinner jsFechaEntrada;
    private javax.swing.JTextField jtfAceite;
    private javax.swing.JTextField jtfBastidor;
    private javax.swing.JTextField jtfCarburante;
    private javax.swing.JTextField jtfConsumo;
    private javax.swing.JTextField jtfDniTrabajadorAsignado;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfMotor;
    private javax.swing.JTextField jtfPotencia;
    private javax.swing.JTextField jtfTiempoDedicado;
    // End of variables declaration//GEN-END:variables

    
}
