/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author novad
 */
public class SelectorConexion extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form SelectorConexion
     */
    int seleccion=0;
    public SelectorConexion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ButtonGroup grupo1 = new ButtonGroup();
        grupo1.add(jrbJDBC);
        grupo1.add(jrbHibernate);
        grupo1.add(jrbObjectDB);
        grupo1.add(jrbMongoDB);
        
        jbAceptar.addActionListener(this);
    }
 
    public void actionPerformed(ActionEvent ae)
    {
        if(ae.getSource() == jbAceptar)
        {
            seleccion=asignarSeleccion();   
            this.dispose();
        }
    }
    public int asignarSeleccion()
    {
        if(jrbJDBC.isSelected())
        {
            seleccion=1;
        }
        else if(jrbHibernate.isSelected())
        {
            seleccion=2;
        }
        else if(jrbObjectDB.isSelected())
        {
            seleccion=3;
        }
        else if(jrbMongoDB.isSelected())
        {
            seleccion=4;
        }
        return seleccion;
    }
    
    public int getSeleccion()
    {
        return seleccion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        jrbMongoDB = new javax.swing.JRadioButton();
        jrbObjectDB = new javax.swing.JRadioButton();
        jrbHibernate = new javax.swing.JRadioButton();
        jrbJDBC = new javax.swing.JRadioButton();
        jlTituloSeleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jbAceptar.setBackground(new java.awt.Color(0, 102, 204));
        jbAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jbAceptar.setText("Aceptar");

        jrbMongoDB.setBackground(new java.awt.Color(255, 255, 255));
        jrbMongoDB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbMongoDB.setText("Mongo DB");

        jrbObjectDB.setBackground(new java.awt.Color(255, 255, 255));
        jrbObjectDB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbObjectDB.setText("Object DB");

        jrbHibernate.setBackground(new java.awt.Color(255, 255, 255));
        jrbHibernate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbHibernate.setText("Hibernate");

        jrbJDBC.setBackground(new java.awt.Color(255, 255, 255));
        jrbJDBC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbJDBC.setText("Java database connection (JDBC)");
        jrbJDBC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlTituloSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        jlTituloSeleccion.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jlTituloSeleccion.setForeground(new java.awt.Color(0, 102, 204));
        jlTituloSeleccion.setText("Seleccionar sistema de base de datos a utilizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbJDBC)
                            .addComponent(jrbHibernate)
                            .addComponent(jrbObjectDB)
                            .addComponent(jrbMongoDB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jlTituloSeleccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jlTituloSeleccion)
                .addGap(18, 18, 18)
                .addComponent(jrbJDBC)
                .addGap(18, 18, 18)
                .addComponent(jrbHibernate)
                .addGap(18, 18, 18)
                .addComponent(jrbObjectDB)
                .addGap(18, 18, 18)
                .addComponent(jrbMongoDB)
                .addGap(18, 18, 18)
                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectorConexion dialog = new SelectorConexion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JLabel jlTituloSeleccion;
    private javax.swing.JRadioButton jrbHibernate;
    private javax.swing.JRadioButton jrbJDBC;
    private javax.swing.JRadioButton jrbMongoDB;
    private javax.swing.JRadioButton jrbObjectDB;
    // End of variables declaration//GEN-END:variables
}
