name: CI

on:
  pull_request:
    paths:
      - '**.java'
      - '**.xml'
      - '**.so'
      - '**.jnilib'
      - '**.dll'
      - '.github/workflows/*.yml'
  push:
    branches:
      - master
    paths:
      - '**.java'
      - '**.xml'
      - '**.so'
      - '**.jnilib'
      - '**.dll'
      - '.github/workflows/*.yml'

jobs:
  test:
    name: test jdk11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-jdk11-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-jdk11-
      - name: Test
        run: mvn test
  test_jdk8:
    name: test jdk8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-jdk8-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-jdk8-
      - name: Test
        run: mvn test
