/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author novad
 */
public class EliminarRepuestos extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form EliminarTrabajador
     */
    boolean confirmarEliminar;
    public EliminarRepuestos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        confirmarEliminar=false;
        
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTituloEliminarVehiculo = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jtfUso = new javax.swing.JTextField();
        jtfFechaCompra = new javax.swing.JTextField();
        jlNumSerie = new javax.swing.JLabel();
        jtfBastidorRepuestos = new javax.swing.JTextField();
        jlReferencia = new javax.swing.JLabel();
        jlTienda = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlNumFacturaRepuestos = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jtfNumFacturaRepuestos = new javax.swing.JTextField();
        jlUso = new javax.swing.JLabel();
        jtfNumSerie = new javax.swing.JTextField();
        jtfReferencia = new javax.swing.JTextField();
        jlFechaCompra = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlBastidorRepuestos = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jtfTienda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlTituloEliminarVehiculo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlTituloEliminarVehiculo.setForeground(new java.awt.Color(255, 0, 0));
        jlTituloEliminarVehiculo.setText("¿Eliminar el siguiente repuesto de la base de datos?");

        jbCancelar.setText("Cancelar");

        jbAceptar.setText("Aceptar");

        jtfUso.setEditable(false);

        jtfFechaCompra.setEditable(false);

        jlNumSerie.setForeground(new java.awt.Color(0, 102, 204));
        jlNumSerie.setText("Número de serie");

        jtfBastidorRepuestos.setEditable(false);

        jlReferencia.setForeground(new java.awt.Color(0, 102, 204));
        jlReferencia.setText("Referencia");

        jlTienda.setForeground(new java.awt.Color(0, 102, 204));
        jlTienda.setText("Tienda");

        jlNombre.setForeground(new java.awt.Color(0, 102, 204));
        jlNombre.setText("Nombre");

        jlNumFacturaRepuestos.setForeground(new java.awt.Color(0, 102, 204));
        jlNumFacturaRepuestos.setText("Número de factura destino");

        jlMarca.setForeground(new java.awt.Color(0, 102, 204));
        jlMarca.setText("Marca");

        jtfNumFacturaRepuestos.setEditable(false);

        jlUso.setForeground(new java.awt.Color(0, 102, 204));
        jlUso.setText("Uso");

        jtfNumSerie.setEditable(false);

        jtfReferencia.setEditable(false);

        jlFechaCompra.setForeground(new java.awt.Color(0, 102, 204));
        jlFechaCompra.setText("Fecha de compra");

        jtfNombre.setEditable(false);

        jlBastidorRepuestos.setForeground(new java.awt.Color(0, 102, 204));
        jlBastidorRepuestos.setText("Bastidor del vehículo destino");

        jtfMarca.setEditable(false);

        jtfTienda.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumSerie)
                    .addComponent(jtfNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBastidorRepuestos)
                    .addComponent(jtfBastidorRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaCompra)
                    .addComponent(jtfFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUso)
                    .addComponent(jtfUso, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTienda)
                    .addComponent(jlNumFacturaRepuestos)
                    .addComponent(jtfNumFacturaRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlReferencia)
                    .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarca)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jlTituloEliminarVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlTituloEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlNumSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlFechaCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBastidorRepuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBastidorRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlReferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlTienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNumFacturaRepuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumFacturaRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void actionPerformed(ActionEvent ae) {
         if(ae.getSource()==jbAceptar)
        {
            confirmarEliminar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarEliminar=false;
            this.dispose();
        }
    }
    
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarEliminar;
    }
    public void setTextoNumSerie(String texto){
        jtfNumSerie.setText(texto);
    }
    public void setTextoReferencia(String texto){
        jtfReferencia.setText(texto);
    }
    public void setTextoNombre(String texto){
        jtfNombre.setText(texto);
    }
    public void setTextoMarca(String texto){
        jtfMarca.setText(texto);
    }
    public void setTextoUso(String texto){
        jtfUso.setText(texto);
    }
    public void setTextoTienda(String texto){
        jtfTienda.setText(texto);
    }
    public void setTextoFechaCompra(String texto){
        jtfFechaCompra.setText(texto);
    }
    
    public void setTextoBastidorRepuestos(String texto){
        jtfBastidorRepuestos.setText(texto);
    }
    public void setTextoNumFacturaRepuestos(String texto){
        jtfNumFacturaRepuestos.setText(texto);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EliminarRepuestos dialog = new EliminarRepuestos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlBastidorRepuestos;
    private javax.swing.JLabel jlFechaCompra;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumFacturaRepuestos;
    private javax.swing.JLabel jlNumSerie;
    private javax.swing.JLabel jlReferencia;
    private javax.swing.JLabel jlTienda;
    private javax.swing.JLabel jlTituloEliminarVehiculo;
    private javax.swing.JLabel jlUso;
    private javax.swing.JTextField jtfBastidorRepuestos;
    private javax.swing.JTextField jtfFechaCompra;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumFacturaRepuestos;
    private javax.swing.JTextField jtfNumSerie;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfTienda;
    private javax.swing.JTextField jtfUso;
    // End of variables declaration//GEN-END:variables

    
}
