/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import com.mycompany.fullauto.controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author novad
 */

public class FormularioRepuestos extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form insertarTrabajador
     */
    private boolean confirmarInsertar;
    private static Controlador controlador;
    public FormularioRepuestos(java.awt.Frame parent, boolean modal,Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador=controlador;
        confirmarInsertar=false;
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
        
        ArrayList<String> listaBastidores = controlador.getListaBastidores();
        for(String bastidor:listaBastidores)
        {
            jcbBastidorRepuestos.addItem(bastidor); 
        }
        ArrayList<String> listaNumsFactura = controlador.getListaNumsFactura();
        for(String numFactura:listaNumsFactura)
        {
            jcbNumFacturaRepuestos.addItem(numFactura); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfUso = new javax.swing.JTextField();
        jlNumSerie = new javax.swing.JLabel();
        jlReferencia = new javax.swing.JLabel();
        jlTienda = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlNumFacturaRepuestos = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlUso = new javax.swing.JLabel();
        jlFormularioRepuestos = new javax.swing.JLabel();
        jtfNumSerie = new javax.swing.JTextField();
        jtfReferencia = new javax.swing.JTextField();
        jlFechaCompra = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlBastidorRepuestos = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jtfTienda = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jsFechaCompra = new javax.swing.JSpinner();
        jcbBastidorRepuestos = new javax.swing.JComboBox<>();
        jcbNumFacturaRepuestos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlNumSerie.setForeground(new java.awt.Color(0, 102, 204));
        jlNumSerie.setText("Número de serie");

        jlReferencia.setForeground(new java.awt.Color(0, 102, 204));
        jlReferencia.setText("Referencia");

        jlTienda.setForeground(new java.awt.Color(0, 102, 204));
        jlTienda.setText("Tienda");

        jlNombre.setForeground(new java.awt.Color(0, 102, 204));
        jlNombre.setText("Nombre");

        jlNumFacturaRepuestos.setForeground(new java.awt.Color(0, 102, 204));
        jlNumFacturaRepuestos.setText("Número de factura destino");

        jlMarca.setForeground(new java.awt.Color(0, 102, 204));
        jlMarca.setText("Marca");

        jlUso.setForeground(new java.awt.Color(0, 102, 204));
        jlUso.setText("Uso");

        jlFormularioRepuestos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlFormularioRepuestos.setForeground(new java.awt.Color(0, 102, 204));
        jlFormularioRepuestos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFormularioRepuestos.setText("Insertar Repuesto");

        jlFechaCompra.setForeground(new java.awt.Color(0, 102, 204));
        jlFechaCompra.setText("Fecha de compra");

        jlBastidorRepuestos.setForeground(new java.awt.Color(0, 102, 204));
        jlBastidorRepuestos.setText("Bastidor del vehículo destino");

        jbCancelar.setText("Cancelar");

        jbAceptar.setText("Aceptar");

        jsFechaCompra.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlFormularioRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumSerie)
                            .addComponent(jtfNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBastidorRepuestos)
                            .addComponent(jlFechaCompra)
                            .addComponent(jlUso)
                            .addComponent(jtfUso, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombre)
                            .addComponent(jcbBastidorRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTienda)
                            .addComponent(jlNumFacturaRepuestos)
                            .addComponent(jlReferencia)
                            .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMarca)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNumFacturaRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jlNumSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlFechaCompra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlFormularioRepuestos)
                        .addGap(47, 47, 47)
                        .addComponent(jlReferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlTienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlBastidorRepuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbBastidorRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNumFacturaRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlNumFacturaRepuestos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioRepuestos dialog = new FormularioRepuestos(new javax.swing.JFrame(), true,controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==jbAceptar)
        {
            confirmarInsertar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarInsertar=false;
            this.dispose();
        }
        
    }
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarInsertar;
    }
    public void desactivarNumSerie()
    {
        jtfNumSerie.setEditable(false);
    }
    
    //Para utilizar el formulario con la función modificar y colocarle los datos que ya existen.
    public void setTextoTitulo(String texto){
        jlFormularioRepuestos.setText(texto);
    }
    public void setTextoNumSerie(String texto){
        jtfNumSerie.setText(texto);
    }
    public void setTextoReferencia(String texto){
        jtfReferencia.setText(texto);
    }
    public void setTextoNombre(String texto){
        jtfNombre.setText(texto);
    }
    public void setTextoMarca(String texto){
        jtfMarca.setText(texto);
    }
    public void setTextoUso(String texto){
        jtfUso.setText(texto);
    }
    public void setTextoTienda(String texto){
        jtfTienda.setText(texto);
    }
    public void setTextoFechaCompra(Date texto){
        jsFechaCompra.setValue(texto);
    }
    
    public void setTextoBastidorRepuestos(String texto){
        jcbBastidorRepuestos.setSelectedItem(texto);
    }
    public void setTextoNumFacturaRepuestos(String texto){
        jcbNumFacturaRepuestos.setSelectedItem(texto);
    }
    
    //Funciones para extraer los datos del formulario.
     public String getNumSerie() {
        return jtfNumSerie.getText();
    }
     public String getReferencia() {
        return jtfReferencia.getText();
    }
    public String getNombre() {
        return jtfNombre.getText();
    }

    public String getMarca() {
        return jtfMarca.getText();
    }
    public String getUso() {
        return jtfUso.getText();
    }
      public String getTienda() {
        return jtfTienda.getText();
    }
    public Date getFechaCompra() {
        return (Date) jsFechaCompra.getValue();
    }

    public String getBastidorVehiculoRepuestos() {
        return jcbBastidorRepuestos.getSelectedItem().toString();
    }
    public String getNumFacturaRepuestos() {
        return jcbNumFacturaRepuestos.getSelectedItem().toString();
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbBastidorRepuestos;
    private javax.swing.JComboBox<String> jcbNumFacturaRepuestos;
    private javax.swing.JLabel jlBastidorRepuestos;
    private javax.swing.JLabel jlFechaCompra;
    private javax.swing.JLabel jlFormularioRepuestos;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumFacturaRepuestos;
    private javax.swing.JLabel jlNumSerie;
    private javax.swing.JLabel jlReferencia;
    private javax.swing.JLabel jlTienda;
    private javax.swing.JLabel jlUso;
    private javax.swing.JSpinner jsFechaCompra;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumSerie;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfTienda;
    private javax.swing.JTextField jtfUso;
    // End of variables declaration//GEN-END:variables

    
}
