/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import com.mycompany.fullauto.controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author novad
 */

public class FormularioInforme extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form insertarTrabajador
     */
    private boolean confirmarInsertar;
    private static Controlador controlador;
    public FormularioInforme(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.controlador=controlador;
        initComponents();
        confirmarInsertar=false;
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
        ArrayList<String> listaDni = controlador.getListaDni();
        for(String dni:listaDni)
        {
            jcbDniTrabajadorInforme.addItem(dni); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlFormularioInforme = new javax.swing.JLabel();
        jtfNumExpedicion = new javax.swing.JTextField();
        jtfTareas = new javax.swing.JTextField();
        jlNumExpedicion = new javax.swing.JLabel();
        jlTareas = new javax.swing.JLabel();
        dniTrabajadorInforme = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbDniTrabajadorInforme = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlFormularioInforme.setBackground(new java.awt.Color(255, 255, 255));
        jlFormularioInforme.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlFormularioInforme.setForeground(new java.awt.Color(0, 102, 204));
        jlFormularioInforme.setText("Insertar informe");

        jlNumExpedicion.setBackground(new java.awt.Color(255, 255, 255));
        jlNumExpedicion.setForeground(new java.awt.Color(0, 102, 204));
        jlNumExpedicion.setText("Número de expedición");

        jlTareas.setForeground(new java.awt.Color(0, 102, 204));
        jlTareas.setText("Tareas");

        dniTrabajadorInforme.setForeground(new java.awt.Color(0, 102, 204));
        dniTrabajadorInforme.setText("DNI del trabajador que generó el informe");

        jbAceptar.setText("Aceptar");

        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDniTrabajadorInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumExpedicion)
                    .addComponent(dniTrabajadorInforme)
                    .addComponent(jlTareas)
                    .addComponent(jtfNumExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jlFormularioInforme)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFormularioInforme)
                .addGap(18, 18, 18)
                .addComponent(jlNumExpedicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(dniTrabajadorInforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbDniTrabajadorInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbAceptar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioInforme dialog = new FormularioInforme(new javax.swing.JFrame(), true,controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==jbAceptar)
        {
            confirmarInsertar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarInsertar=false;
            this.dispose();
        }
        
    }
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarInsertar;
    }
    //Para utilizar el formulario con la función modificar y colocarle los datos que ya existen.
    public void setTextoTitulo(String texto){
        jlFormularioInforme.setText(texto);
    }
    public void setTextoNumExpedicion(String texto){
        jtfNumExpedicion.setText(texto);
    }
    public void setTextoTareas(String texto){
        jtfTareas.setText(texto);
    }
    public void setTextoDniTrabajadorInforme(String texto){
        jcbDniTrabajadorInforme.setSelectedItem(texto);
    }
    public void desactivarNumExpedicion()
    {
        jtfNumExpedicion.setEditable(false);
    }
    
    public String getNumExpedicion(){
        return jtfNumExpedicion.getText();
    }
    public String getTareas(){
       return jtfTareas.getText();
    }
    public String getDniTrabajadorInforme(){
        return jcbDniTrabajadorInforme.getSelectedItem().toString();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dniTrabajadorInforme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbDniTrabajadorInforme;
    private javax.swing.JLabel jlFormularioInforme;
    private javax.swing.JLabel jlNumExpedicion;
    private javax.swing.JLabel jlTareas;
    private javax.swing.JTextField jtfNumExpedicion;
    private javax.swing.JTextField jtfTareas;
    // End of variables declaration//GEN-END:variables

    
}
