/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author novad
 */

public class FormularioFactura extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form insertarTrabajador
     */
    private boolean confirmarInsertar;
    public FormularioFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        confirmarInsertar=false;
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNumExpedicionInforme = new javax.swing.JLabel();
        jlFormularioFactura = new javax.swing.JLabel();
        jtfNumFactura = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jtfLineaFactura = new javax.swing.JTextField();
        jtfNumExpedicionInforme = new javax.swing.JTextField();
        jlNumFactura = new javax.swing.JLabel();
        jlPrecioFactura = new javax.swing.JLabel();
        jlLineaFactura = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlNumExpedicionInforme.setForeground(new java.awt.Color(0, 102, 204));
        jlNumExpedicionInforme.setText("Número de expedición del informe asociado");

        jlFormularioFactura.setBackground(new java.awt.Color(255, 255, 255));
        jlFormularioFactura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlFormularioFactura.setForeground(new java.awt.Color(0, 102, 204));
        jlFormularioFactura.setText("Insertar Factura");

        jlNumFactura.setBackground(new java.awt.Color(255, 255, 255));
        jlNumFactura.setForeground(new java.awt.Color(0, 102, 204));
        jlNumFactura.setText("Número de factura");

        jlPrecioFactura.setForeground(new java.awt.Color(0, 102, 204));
        jlPrecioFactura.setText("Precio");

        jlLineaFactura.setForeground(new java.awt.Color(0, 102, 204));
        jlLineaFactura.setText("Líneas factura");

        jbAceptar.setText("Aceptar");

        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumExpedicionInforme)
                    .addComponent(jtfLineaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumExpedicionInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumFactura)
                    .addComponent(jlLineaFactura)
                    .addComponent(jlPrecioFactura)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jlFormularioFactura)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFormularioFactura)
                .addGap(18, 18, 18)
                .addComponent(jlNumFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPrecioFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlLineaFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLineaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNumExpedicionInforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumExpedicionInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbAceptar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioFactura dialog = new FormularioFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==jbAceptar)
        {
            confirmarInsertar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarInsertar=false;
            this.dispose();
        }
        
    }
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarInsertar;
    }
    //Para utilizar el formulario con la función modificar y colocarle los datos que ya existen.
    public void setTextoTitulo(String texto){
        jlFormularioFactura.setText(texto);
    }
    public void setTextoNumFactura(String texto){
        jtfNumFactura.setText(texto);
    }
    public void setTextoPrecio(String texto){
        jtfPrecio.setText(texto);
    }
    public void setTextoLineaFactura(String texto){
        jtfLineaFactura.setText(texto);
    }
    public void setTextoNumExpedicionInforme(String texto){
        jtfNumExpedicionInforme.setText(texto);
    }
    public void desactivarNumFactura()
    {
        jtfNumFactura.setEditable(false);
    }
  
    //Funciones para extraer los datos del formulario.
     public String getNumFactura() {
        return jtfNumFactura.getText();
    }
     public String getPrecio() {
        return jtfPrecio.getText();
    }
    public String getLineaFactura() {
        return jtfLineaFactura.getText();
    }
    public String getNumExpedicionInforme() {
        return jtfNumExpedicionInforme.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlFormularioFactura;
    private javax.swing.JLabel jlLineaFactura;
    private javax.swing.JLabel jlNumExpedicionInforme;
    private javax.swing.JLabel jlNumFactura;
    private javax.swing.JLabel jlPrecioFactura;
    private javax.swing.JTextField jtfLineaFactura;
    private javax.swing.JTextField jtfNumExpedicionInforme;
    private javax.swing.JTextField jtfNumFactura;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables

    
}
