/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

import com.mycompany.fullauto.controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author novad
 */

public class FormularioObd extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form insertarTrabajador
     */
    private boolean confirmarInsertar;
    private static Controlador controlador;
    public FormularioObd(java.awt.Frame parent, boolean modal,Controlador controlador) {
        super(parent, modal);
        this.controlador=controlador;
        initComponents();
        confirmarInsertar=false;
        jbAceptar.addActionListener(this);
        jbCancelar.addActionListener(this);
        
        ArrayList<String> listaBastidores = controlador.getListaBastidores();
        for(String bastidor:listaBastidores)
        {
            jcbBastidorObd.addItem(bastidor); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfTempAceite = new javax.swing.JTextField();
        jtfTempAgua = new javax.swing.JTextField();
        jlId = new javax.swing.JLabel();
        jtfCodSalida = new javax.swing.JTextField();
        jlRmpInst = new javax.swing.JLabel();
        jlBastidorObd = new javax.swing.JLabel();
        jlTempAceite = new javax.swing.JLabel();
        jlFormularioObd = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfRpmInst = new javax.swing.JTextField();
        jlTempAgua = new javax.swing.JLabel();
        jlCodSalida = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jlSensores = new javax.swing.JLabel();
        jtfSensores = new javax.swing.JTextField();
        jcbBastidorObd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlId.setForeground(new java.awt.Color(0, 102, 204));
        jlId.setText("Id");

        jlRmpInst.setForeground(new java.awt.Color(0, 102, 204));
        jlRmpInst.setText("RPM instantáneas");

        jlBastidorObd.setForeground(new java.awt.Color(0, 102, 204));
        jlBastidorObd.setText("Bastidor del vehículo ");

        jlTempAceite.setForeground(new java.awt.Color(0, 102, 204));
        jlTempAceite.setText("Temperatura aceite");

        jlFormularioObd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlFormularioObd.setForeground(new java.awt.Color(0, 102, 204));
        jlFormularioObd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFormularioObd.setText("Insertar Obd");

        jlTempAgua.setForeground(new java.awt.Color(0, 102, 204));
        jlTempAgua.setText("Temperatura anticongelante");

        jlCodSalida.setForeground(new java.awt.Color(0, 102, 204));
        jlCodSalida.setText("Código de salida");

        jbCancelar.setText("Cancelar");

        jbAceptar.setText("Aceptar");

        jlSensores.setForeground(new java.awt.Color(0, 102, 204));
        jlSensores.setText("Sensores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlFormularioObd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSensores)
                            .addComponent(jtfSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBastidorObd)
                            .addComponent(jcbBastidorObd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlId)
                                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCodSalida)
                                    .addComponent(jtfCodSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfRpmInst, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlRmpInst))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTempAceite)
                                    .addComponent(jtfTempAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlTempAgua)
                                    .addComponent(jtfTempAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRmpInst)
                            .addComponent(jlTempAceite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRpmInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTempAceite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlFormularioObd)
                        .addGap(120, 120, 120)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodSalida)
                    .addComponent(jlTempAgua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTempAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSensores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlBastidorObd)
                .addGap(18, 18, 18)
                .addComponent(jcbBastidorObd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioObd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioObd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioObd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioObd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioObd dialog = new FormularioObd(new javax.swing.JFrame(), true,controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==jbAceptar)
        {
            confirmarInsertar=true;
            this.dispose();
        }
        if(ae.getSource()==jbCancelar)
        {
            confirmarInsertar=false;
            this.dispose();
        }
        
    }
    public void desactivarIdObd()
    {
        jtfId.setEditable(false);
    }
    //Para extraer si el usuario ha pulsado en aceptar o no.
    public boolean getConfirmacion() {
        return confirmarInsertar;
    }
    //Para utilizar el formulario con la función modificar y colocarle los datos que ya existen.
    public void setTextoTitulo(String texto){
        jlFormularioObd.setText(texto);
    }
    public void setTextoId(String texto){
        jtfId.setText(texto);
    }
    public void setTextoRpmInst(String texto){
        jtfRpmInst.setText(texto);
    }
    
    public void setTextoTempAceite(String texto){
        jtfTempAceite.setText(texto);
    }
    public void setTextoTempAgua(String texto){
        jtfTempAgua.setText(texto);
    }
    public void setTextoCodSalida(String texto){
        jtfCodSalida.setText(texto);
    }
    public void setTextoSensores(String texto){
        jtfSensores.setText(texto);
    }
    
    public void setTextoBastidorObd(String texto){
        jcbBastidorObd.setSelectedItem(texto);
    }
    
    //Funciones para extraer los datos del formulario.
    public String getId() {
        return jtfId.getText();
    }
    public String getRpmInst() {
        return jtfRpmInst.getText();
    }
    public String getTempAceite() {
        return jtfTempAceite.getText();
    }
    public String getTempAgua() {
        return jtfTempAgua.getText();
    }
    public String getCodSalida() {
        return jtfCodSalida.getText();
    }
    public String getSensores(){
        return jtfSensores.getText();
    }
    
    public String getBastidorObd(){
        return jcbBastidorObd.getSelectedItem().toString();
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbBastidorObd;
    private javax.swing.JLabel jlBastidorObd;
    private javax.swing.JLabel jlCodSalida;
    private javax.swing.JLabel jlFormularioObd;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlRmpInst;
    private javax.swing.JLabel jlSensores;
    private javax.swing.JLabel jlTempAceite;
    private javax.swing.JLabel jlTempAgua;
    private javax.swing.JTextField jtfCodSalida;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfRpmInst;
    private javax.swing.JTextField jtfSensores;
    private javax.swing.JTextField jtfTempAceite;
    private javax.swing.JTextField jtfTempAgua;
    // End of variables declaration//GEN-END:variables

    
}
