/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fullauto.vista;

/**
 *
 * @author novad
 */
public class SeleccionConexion extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionConexion
     */
    public SeleccionConexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTituloSeleccion = new javax.swing.JLabel();
        jrbJDBC = new javax.swing.JRadioButton();
        jrbHibernate = new javax.swing.JRadioButton();
        jrbObjectDB = new javax.swing.JRadioButton();
        jrbMongoDB = new javax.swing.JRadioButton();

        jlTituloSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        jlTituloSeleccion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlTituloSeleccion.setForeground(new java.awt.Color(51, 102, 255));
        jlTituloSeleccion.setText("Seleccionar tipo de base de datos a utilizar");

        jrbJDBC.setText("Java database connection (JDBC)");

        jrbHibernate.setText("Hibernate");

        jrbObjectDB.setText("Object DB");

        jrbMongoDB.setText("Mongo DB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbJDBC)
                    .addComponent(jlTituloSeleccion)
                    .addComponent(jrbHibernate)
                    .addComponent(jrbObjectDB)
                    .addComponent(jrbMongoDB))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlTituloSeleccion)
                .addGap(18, 18, 18)
                .addComponent(jrbJDBC)
                .addGap(18, 18, 18)
                .addComponent(jrbHibernate)
                .addGap(18, 18, 18)
                .addComponent(jrbObjectDB)
                .addGap(18, 18, 18)
                .addComponent(jrbMongoDB)
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlTituloSeleccion;
    private javax.swing.JRadioButton jrbHibernate;
    private javax.swing.JRadioButton jrbJDBC;
    private javax.swing.JRadioButton jrbMongoDB;
    private javax.swing.JRadioButton jrbObjectDB;
    // End of variables declaration//GEN-END:variables
}
